### ISSUE TITLE
Issues with make install

### ISSUE THREAD

**Issue by duckunix** [jonathanabennett/projectwarrior#5]
Seems that the requirements are not documented:

    make install
    sbcl --load gtd-review.asd \
            --eval '(ql:quickload :gtd-review)' \
            --eval '(asdf:make :gtd-review)' \
            --eval '(quit)'
    This is SBCL 2.1.1, an implementation of ANSI Common Lisp.
    More information about SBCL is available at <http://www.sbcl.org/>.
    
    SBCL is free software, provided as is, with absolutely no warranty.
    It is mostly in the public domain; some portions are provided under
    BSD-style licenses.  See the CREDITS and COPYING files in the
    distribution for more information.
    
    debugger invoked on a SB-C::INPUT-ERROR-IN-LOAD in thread
    #<THREAD "main thread" RUNNING {1001878103}>:
      READ error during LOAD:
    
        Package ASDF does not exist.
    
          Line: 3, Column: 15, File-Position: 35
    
          Stream: #<SB-INT:FORM-TRACKING-STREAM for "file /home/don/tmp/gtd-review/gtd-review.asd" {10009EA1E3}>
    
    Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.
    
    restarts (invokable by number or by possibly-abbreviated name):
      0: [ABORT   ] Abort loading file "/home/don/tmp/gtd-review/gtd-review.asd".
      1: [CONTINUE] Ignore runtime option --load "gtd-review.asd".
      2:            Skip rest of --eval and --load options.
      3:            Skip to toplevel READ/EVAL/PRINT loop.
      4: [EXIT    ] Exit SBCL (calling #'EXIT, killing the process).
    
    (SB-C:COMPILER-ERROR SB-C::INPUT-ERROR-IN-LOAD :CONDITION #<SB-INT:SIMPLE-READER-PACKAGE-ERROR "Package ~A does not exist." {10009EC093}> :STREAM #<SB-INT:FORM-TRACKING-STREAM for "file /home/don/tmp/gtd-review/gtd-review.asd" {10009EA1E3}>)
    0] 

I have no clue about Lisp, as I expect most folks now days.

**Comment by jonathanabennett** [comment]
I believe the latest version of master should fix it. Can you clone that and try again?

**Comment by jonathanabennett** [comment]
Whoops! Still learning Github. I don't want to close this until I know it has worked for you.

**Comment by duckunix** [comment]
No, it is still not working:

    22:21:44 [don:~/tmp/gtd-review] master ± git pull
    Already up to date.
    22:21:49 [don:~/tmp/gtd-review] master ± make install
    sbcl --eval "(require 'asdf)" \
            --load gtd-review.asd \
            --eval '(ql:quickload :gtd-review)' \
            --eval '(asdf:make :gtd-review)' \
            --eval '(quit)'
    This is SBCL 2.1.1, an implementation of ANSI Common Lisp.
    More information about SBCL is available at <http://www.sbcl.org/>.
    
    SBCL is free software, provided as is, with absolutely no warranty.
    It is mostly in the public domain; some portions are provided under
    BSD-style licenses.  See the CREDITS and COPYING files in the
    distribution for more information.
    
    debugger invoked on a SB-INT:SIMPLE-READER-PACKAGE-ERROR in thread
    #<THREAD "main thread" RUNNING {1001878103}>:
      Package QL does not exist.
    
        Stream: #<dynamic-extent STRING-INPUT-STREAM (unavailable) from "(ql:quic...">
    
    Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.
    
    restarts (invokable by number or by possibly-abbreviated name):
      0: [CONTINUE ] Use the current package, COMMON-LISP-USER.
      1: [RETRY    ] Retry finding the package.
      2: [USE-VALUE] Specify a different package
      3: [UNINTERN ] Read the symbol as uninterned.
      4: [SYMBOL   ] Specify a symbol to return
      5:             Ignore runtime option --eval "(ql:quickload :gtd-review)".
      6: [ABORT    ] Skip rest of --eval and --load options.
      7:             Skip to toplevel READ/EVAL/PRINT loop.
      8: [EXIT     ] Exit SBCL (calling #'EXIT, killing the process).
    
    (SB-IMPL::READER-FIND-PACKAGE "QL" #<SB-IMPL::STRING-INPUT-STREAM {7FBE17B27993}> T)
    0]

**Comment by jonathanabennett** [comment]
Ah, quicklisp is listed in that paragraph leading into the installation instructions. It can be installed like so: https://www.quicklisp.org/beta/

I will amend the installation instructions to make the prerequisites an explicit list with links to both sbcl and quicklisp to make it easier to ensure they're met.

**Comment by duckunix** [comment]
Thanks.  Closes I ever came to dealing with lisp was running emacs a long time ago.  Spoon feed the install, please. :)
